server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mysql://localhost:3306/booking_management}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    password: ${DBMS_PASSWORD:}
    username: ${DBMS_USERNAME:root}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  signerKey:
  valid-duration: 6000 # in second
  refreshable-duration: 36000 # in seconds
